version: '3.9'

services:
  
  web:
    image: ratatata/cryptobot:latest
    build:
      context: CryptoBot
      dockerfile: Dockerfile 
    networks:
      - host_network
    depends_on:
      - db
    environment:
      - DOTNET_ENVIRONMENT=Local
      - ASPNETCORE_ENVIRONMENT=Local

  db:
    image: postgres:latest
    container_name: db
    hostname: db
    environment:
      POSTGRES_PASSWORD: Qwerty123
    networks:
      - host_network
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
    ports:
      - "1433:1433"
  
networks:
  host_network:
    name: 'host_network'

volumes:
  postgresql_volume:
    name: 'cryptobot_postgresql_volume'