version: '3.9'

services:
  
  web:
    build:
      context: .
      dockerfile: CryptoBot/Dockerfile 
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: microsoft/mssql-server-linux:latest
    environment:
      SA_PASSWORD: "TestPassword123!"
      ACCEPT_EULA: "Y"
    networks:
      - host_network
    volumes:
      - mssql_volume:/var/opt/mssql
  
networks:
  host_network:
    name: 'host_network'
    driver: bridge

volumes:
  mssql_volume:
    name: 'myblog_mssql_volume'