version: '3.9'

services:
  
  web:
    build:
      context: .
      dockerfile: CryptoBot/Dockerfile 
    networks:
      - host_network
    depends_on:
      - db
    environment:
      - DOTNET_ENVIRONMENT=Local
      - ASPNETCORE_ENVIRONMENT=Local

  db:
    image: mcr.microsoft.com/mssql/server
    container_name: db
    hostname: db
    environment:
      MSSQL_SA_PASSWORD: VeryStron!!!!gg231Passo123#@2
      ACCEPT_EULA: "Y"
    networks:
      - host_network
    volumes:
      - mssql_volume:/var/opt/mssql
    ports:
      - "1433:1433"
  
networks:
  host_network:
    name: 'host_network'

volumes:
  mssql_volume:
    name: 'cryptobot_mssql_volume'