version: '3.9'

services:
  
  web:
    build:
      context: .
      dockerfile: CryptoBot/Dockerfile 
    networks:
      - host_network
    depends_on:
      - db
    environment:
      - DOTNET_ENVIRONMENT='Local'

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "TestPassword123!"
      ACCEPT_EULA: "Y"
    networks:
      - host_network
    volumes:
      - mssql_volume:/var/opt/mssql
  
networks:
  host_network:
    name: 'host_network'
    driver: bridge

volumes:
  mssql_volume:
    name: 'cryptobot_mssql_volume'